INSERT INTO excuse (excuse_text) VALUES
    ("I couldn't make it because my pet rock needed emotional support."),
    ("My toaster and I had a heated argument, and I needed some time to cool off."),
    ("I accidentally joined a salsa dancing class, and the spicy moves left me too exhausted."),
    ("I got stuck in a time loop trying to teach my cat quantum physics."),
    ("The aliens needed my help decoding their intergalactic grocery list."),
    ("I was abducted by ninja squirrels demanding acorns as ransom."),
    ("My psychic told me I needed to avoid all gatherings for the sake of global harmony."),
    ("I was on a top-secret mission to find the missing sock from the laundry."),
    ("I got lost in thought. It's unfamiliar territory for me."),
    ("A parallel universe version of me needed advice on parallel parking."),
    ("I was trapped in an elevator with a mime, and communication was a struggle."),
    ("My WiFi went on strike, so I had to negotiate with the modem."),
    ("I was busy perfecting my invisibility cloak, but I haven't quite mastered it yet."),
    ("I was held hostage by a particularly gripping book and couldn't put it down."),
    ("I was practicing my interpretive dance routine for interpretive reasons."),
    ("My rubber duck needed therapy, and I was the designated listener."),
    ("I was trapped in a TikTok time warp, and the minutes turned into hours."),
    ("I was on a quest to find the mythical lost TV remote."),
    ("I was caught in a heated debate with my GPS about the best route."),
    ("I accidentally volunteered as tribute for a game of hide-and-seek with invisible friends."),
    ("I was busy attending a virtual reality support group for characters stuck in video games."),
    ("I was on a secret mission to retrieve all the socks that vanished in the laundry."),
    ("My shadow got offended, so I had to apologize and make amends."),
    ("I was on a quest to find the end of the rainbow to claim my pot of coffee."),
    ("I was caught in a staring contest with my reflection, and it was a tie."),
    ("My GPS took me to a parallel universe, and the roads were too confusing."),
    ("I got stuck in a YouTube tutorial loop on how to be less indecisive."),
    ("I was trying to convince my mirror reflection to do all my chores."),
    ("I was on a top-secret mission to infiltrate the cookie jar without making a sound."),
    ("I was busy perfecting my karaoke skills in the shower."),
    ("My houseplants staged a rebellion, and I had to negotiate a peace treaty."),
    ("I was busy counting the wrinkles on my pet turtle."),
    ("I was abducted by time-traveling donuts, and we had a deep-fried conversation."),
    ("I was on a quest to find the missing sock, which turned out to be a sockpuppet uprising."),
    ("I was stuck in a game of hide-and-seek with my invisible friend."),
    ("I was helping the squirrels organize a flash mob in the park."),
    ("I had to participate in a marathon of bad hair days."),
    ("My inner child needed playtime, and the adult in me couldn't say no."),
    ("I was caught in a dance-off with the neighbor's scarecrow."),
    ("I was busy searching for the remote control, which mysteriously vanished into the sofa abyss."),
    ("I was participating in a competitive nap-taking championship."),
    ("My keyboard and I had a disagreement, and it needed time to cool down."),
    ("I was on a mission to find the secret ingredient in my grandma's cookies."),
    ("I was held captive by a gripping novel, and the characters refused to release me."),
    ("I was trapped in a bubble wrap popping marathon."),
    ("I had to console my refrigerator; it was feeling a bit cold and lonely."),
    ("I was stuck in a debate with my mirror reflection over who has the better hairstyle."),
    ("I was on a quest to find the end of the internet."),
    ("I was participating in a snail racing championship, and things got intense."),
    ("I was trapped in a game of charades with my furniture, and it was winning."),
    ("I was on a top-secret mission to decode the language of squirrels."),
    ("I got caught up in a heated debate with my GPS about the meaning of 'recalculating.'"),
    ("My pet goldfish had an existential crisis, and I needed to provide emotional support."),
    ("I was practicing my juggling skills with rubber chickens and lost track of time."),
    ("I got trapped in a staring contest with a hypnotic lava lamp."),
    ("I was on a quest to find the lost city of Wi-Fi signals."),
    ("My alarm clock and I had a disagreement, and it refused to wake me up."),
    ("I was trying to teach my pet rock to roll, and it was a slow process."),
    ("I was busy participating in a support group for recovering procrastinators."),
    ("I got stuck in a revolving door, and it became a philosophical reflection on life's cycles."),
    ("I was trapped in a heated debate with my shadow over who's the better dancer."),
    ("I was on a mission to find the mythical land of missing socks."),
    ("My refrigerator was feeling too cold, so I had to give it a warm hug."),
    ("I was practicing my interpretive dance moves for the interpretive dance-off."),
    ("I had to attend a virtual reality seminar for learning how to deal with non-existent problems."),
    ("I was caught in a fierce thumb wrestling match with my left hand."),
    ("I got stuck in a time loop trying to perfect the art of doing nothing."),
    ("My fortune cookie predicted a day of extreme horizontal activities, so I took it easy."),
    ("I was on a mission to break the world record for the longest nap."),
    ("I was participating in a synchronized swimming competition in my bathtub."),
    ("I got caught in a rain of marshmallows, and I had to wait for it to stop."),
    ("My invisible friend challenged me to an invisible chess match, and it was intense."),
    ("I was busy trying to understand why some people believe that the Earth is flat."),
    ("I was on a quest to find the end of the rainbow and claim my pot of virtual gold."),
    ("My mirror and I got into a debate about who's the fairest, and we needed a resolution."),
    ("I was held hostage by a gripping story, and the characters wouldn't let me go."),
    ("I got trapped in a game of hide-and-seek with my shadow."),
    ("I was on a mission to find the missing sock, which turned out to be on a solo vacation."),
    ("I was participating in a speed-walking competition, but I lost track of time."),
    ("My keyboard needed a break from typing, so I let it rest for a while."),
    ("I was on a quest to find the lost city of mismatched socks."),
    ("I got caught in a heated argument with my mirror over who has the better reflection."),
    ("I was stuck in a staring contest with a mesmerizing lava lamp."),
    ("I was practicing my interpretive dance moves for an interpretive dance marathon."),
    ("I got caught up in a debate with my GPS over the most scenic route."),
    ("I was on a mission to teach my cat the art of meditation."),
    ("My refrigerator was feeling too chilly, so I had to warm it up with a blanket."),
    ("I was participating in a contest to see who could take the longest nap."),
    ("I got trapped in a revolving door and pondered the meaning of life's cycles."),
    ("I was on a quest to find the end of the internet, but it seemed endless."),
    ("I was busy having a staring contest with a mesmerizing lava lamp."),
    ("My alarm clock and I had a disagreement, so it refused to wake me up."),
    ("I was on a mission to find the mythical land where lost socks go."),
    ("I got caught in a time loop trying to perfect the art of doing absolutely nothing."),
    ("I was practicing my interpretive dance moves for the interpretive dance-off championship."),
    ("I was participating in a synchronized sleeping competition in my dreams."),
    ("My pet rock needed a spa day, and I had to pamper it with positive energy."),
    ("I was on a quest to find the lost city of mismatched socks."),
    ("I got caught in a heated debate with my shadow over who's the better dancer."),
    ("I was busy attending a virtual reality support group for characters stuck in old video games.");